### ISSUE TITLE
Add contract history slice to wallet

### ISSUE THREAD

**Issue by kastolars** [SIGBlockchain/aurum_client#33]
We will introduce contract histories in our wallet so that people can view the history of all their transactions made.
- [x] Create a struct called `ContractSummary`, should have a field that designates "to" or "from", a recipient wallet address, and an amount
- [x] Add a field to the wallet that is a slice of these structs
- [x] Confirm that it's added to the json wallet.

**Comment by arosso3** [comment]
I created the struct and added a slice of them to the wallet. How do I confirm that it is added to the JSON wallet?

**Comment by kastolars** [comment]
> 
> 
> I created the struct and added a slice of them to the wallet. How do I confirm that it is added to the JSON wallet?

You should be able to load the wallet contents using the json package to a wallet struct which contains a slice of that struct. The test can just be asserting that that field exists when creating a new wallet.
