### ISSUE TITLE
MAC release

### ISSUE THREAD

**Issue by kastolars** [SIGBlockchain/aurum_client#8]
- [x] make a branch based off `dev` called `mac_release`
- [x] at project root, run `go build -o client`
- [x] remove `main.go`
- [x] remove `internal/` (yes the whole directory)
- [x] test to make sure that `client -h` works

No pull request is needed, all this code remains on this branch.

**Comment by bashbashbash** [comment]
This issue is complete - I will await a confirmation from a CO before closing
