### ISSUE TITLE
Windows release

### ISSUE THREAD

**Issue by kastolars** [SIGBlockchain/aurum_client#9]
- [ ] make a branch based off `dev` called `windows_release`
- [ ] at project root, run `go build -o client`
- [ ] remove `main.go`
- [ ] remove `internal/` (yes the whole directory)
- [ ] test to make sure that `client -h` works

No pull request is needed, all this code remains on this branch.

**Comment by Vineet77** [comment]
The branch is up and ready.

**Comment by Vineet77** [comment]
Can confirm it works on Windows x86-64
